"""empty message

Revision ID: fd0128e95d67
Revises: 92a72e3adb62
Create Date: 2021-04-11 21:22:09.646912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0128e95d67'
down_revision = '92a72e3adb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook', sa.Column('video_id', sa.String(length=300), nullable=True))
    op.drop_column('cook', 'video_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook', sa.Column('video_link', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('cook', 'video_id')
    # ### end Alembic commands ###
